---
# tasks file for ntp-role

### invoke ../package_installation.yml
- name: tasks/package_installation.yml
  ansible.builtin.include_tasks:
    file: "package_installation.yml"

### Fetch chrony.conf file formed jinja tmplate
- name: Fetch chrony.conf file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: "Restart chronyd"
